FROM golang:1.17-alpine AS dev
WORKDIR /workspaces/nijisanji-songs-announcement
COPY go.mod go.sum ./
RUN go mod download
RUN go get -u github.com/cosmtrek/air
RUN apk add git
RUN go install -v golang.org/x/tools/gopls@latest
RUN go install -v github.com/ramya-rao-a/go-outline@latest
COPY . ./
EXPOSE 8081
