// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Video struct {
	ID                 string
	Title              string
	Songconfirm        int32
	ScheduledStartTime time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Vtuber struct {
	ID        string
	Name      string
	ItemCount int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
